import { Banner } from '@/components/Banner'
import { ProductsGrid } from '@/components/ProductsGrid'
import { SearchInput } from '@/components/SearchInput'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header className="bg-[#F9F9FB] px-6 pb-8">
          {/* TOP */}
          <div className="flex justify-between pt-9">
            <div className="flex items-center justify-between w-full">
              <h3 className="font-medium text-[24px] tetx-[#1b1b1b]">
                Seja Bem-Vindo 👋
              </h3>

              <div className="flex flex-col gap-1 w-4 h-4 justify-between cursor-pointer">
                <div className="h-[2px] bg-orange-500 w-full"></div>
                <div className="h-[2px] bg-orange-500 w-full"></div>
                <div className="h-[2px] bg-orange-500 w-full"></div>
              </div>
            </div>
          </div>

          <p className="text-base font-normal mt-[8px] text-[#979797CC] mb-7">
            O que deseja para hoje?
          </p>

          <div className="bottom">
            <SearchInput
              onSearch={searchTerm => console.log(searchTerm)}
              mainColor="#FB9400"
              placeholder="Digite o nome do produto"
            />
          </div>
        </header>

        <section className="mx-6">
          <Banner images={['/images/banner-1.png', '/images/banner-2.png']} />
        </section>

        <section className="mx-6 mt-6">
          <ProductsGrid />
        </section>
      </main>
    </>
  )
}
